### ISSUE TITLE
Secret File missing from config folder

### ISSUE THREAD

**Issue by dbhagesh** [Qhkm92/fiverr-clone-v2#1]
Secret file is missing from the config folder of your project. Please update it.

**Comment by madusankapremaratne** [comment]
Unusable due to the particular issue. secret file not found

**Comment by aayani** [comment]
Although I haven't setup the project, but figured _secret.js_ file to be structured like this:
```
{
  port: 3000,
  secret: "<<CHANGE_ME>>",
  database: "<<CHANGE_ME>>",
  algolia_appId: "<<CHANGE_ME>>",
  algolia_api_key: "<<CHANGE_ME>>",
}
```

**Comment by ibrahim0099** [comment]
Yes, the file is missing & possible solution is  

1) Install nodemon by this command npm i nodemon
2) Make secret.js file inside config folder
3) Write Following Code in secret.js

const secret = {
    port: 3000,
    secret: "testing",
    database: "mongodb://localhost:27017/<Your Database Name>",  // "mongodb://localhost:27017/fiverrApp"
    algolia_appId: "Your_API_Id",  // You can get it from this link https://www.algolia.com/users/sign_in
    algolia_api_key: "Your_API_Key",
  }

module.exports = secret

Hope this will helpful

**Comment by madhusudhanj7** [comment]
after going through the above solution, still unable to fix the issue.

> marketplace@1.0.0 start /Users/madhusudhanj/Desktop/MERN-fiverr-clone/fiverr-clone-v2
> nodemon server.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
/Users/madhusudhanj/Desktop/MERN-fiverr-clone/fiverr-clone-v2/server.js:7
const MongoStore = require('connect-mongo')(session);
                                           ^

TypeError: Class constructor MongoStore cannot be invoked without 'new'
    at Object.<anonymous> (/Users/madhusudhanj/Desktop/MERN-fiverr-clone/fiverr-clone-v2/server.js:7:44)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...

**Comment by madhusudhanj7** [comment]
https://forum.freecodecamp.org/t/advanced-node-and-express-error/450979/2

**Comment by ibrahim0099** [comment]
Hello, Thank you so much for reaching out to me for this issue. I would glad to help you get this project run on your system.

Let's schedule a call session tomorrow so that I can guide you better.


________________________________

**Comment by madhusudhanj7** [comment]
Hi Ibrahim,
Thanks for replying, we are able to set up a project on our system but a
couple of features are not working as expected. can you help us out to
resolve this issue?
Thanks in advance.

**Comment by sachincrimsoni** [comment]
Please help me. I'm facing below issues  =>


[nodemon] starting `node server.js`
(node:13232) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Running on port 3000

D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb\lib\mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:198:13)
    at Connection.<anonymous> (D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at Socket.<anonymous> (D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by aayani** [comment]
> Please help me. I'm facing below issues =>
> 
> [nodemon] starting `node server.js`
> (node:13232) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
> Running on port 3000
> 
> D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb\lib\mongo_client.js:421
> throw err
> ^
> MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
> at Pool. (D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb-core\lib\topologies\server.js:336:35)
> at Pool.emit (events.js:198:13)
> at Connection. (D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb-core\lib\connection\pool.js:280:12)
> at Object.onceWrapper (events.js:286:20)
> at Connection.emit (events.js:198:13)
> at Socket. (D:\htdocs\REACT\fiverr-clone\fiverr-clone-v2\node_modules\mongodb-core\lib\connection\connection.js:189:49)
> at Object.onceWrapper (events.js:286:20)
> at Socket.emit (events.js:198:13)
> at emitErrorNT (internal/streams/destroy.js:91:8)
> at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> [nodemon] app crashed - waiting for file changes before starting...

It seems like your MongoDB is not up and running. Have you checked your connection?
